language: scala
sudo: required
os: linux
dist: trusty
jdk: oraclejdk8

scala:
  - "2.11.12"

before_script:
 - docker-compose build $TEST_ENV

script:
 - docker-compose run $TEST_ENV
 - if [[ "$TEST_ENV" = *llvm-6.0 ]]; then
     export VERSION="${TRAVIS_COMMIT}";
     docker-compose build bindgen;
     find . -name target | xargs sudo rm -rf;
     scripts/docker-test.sh;
   fi

matrix:
  include:
  - env: TEST_ENV=ubuntu-18.04-llvm-6.0
  - env: TEST_ENV=ubuntu-18.04-llvm-5.0
  - env: TEST_ENV=formatting
    before_script:
    - clang-format --version 
    script:
    - scripts/scalafmt --test;
    - scripts/clangfmt --test;

before_cache:
  # See https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs sudo rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs sudo rm

cache:
  directories:
   - "$HOME/.ivy2/cache"
   - "$HOME/.sbt/boot/scala-*"
   - "$HOME/.coursier"
