language: cpp
sudo: required
compiler: gcc

script:
 - docker-compose build $TEST_ENV
 - docker-compose run $TEST_ENV
 - if [[ "$TEST_ENV" = *llvm-5.0 ]]; then
     docker-compose run --rm $TEST_ENV scripts/scalafmt --test;
     docker-compose run --rm $TEST_ENV scripts/clangfmt --test;
   fi
 - if [[ "$TEST_ENV" = *llvm-6.0 ]]; then
     export VERSION="${TRAVIS_COMMIT}";
     docker-compose build bindgen;
     find . -name target | xargs sudo rm -rf;
     scripts/docker-test.sh;
   fi

matrix:
  include:
  - env: TEST_ENV=ubuntu-18.04-llvm-6.0
    deploy:
    - provider: script
      script: scripts/docker-deploy.sh "$TRAVIS_COMMIT" "$TRAVIS_TAG"
      on:
        tags: true
    - provider: script
      script: scripts/docker-deploy.sh "$TRAVIS_COMMIT" latest
      on:
        branch: master
  - env: TEST_ENV=ubuntu-18.04-llvm-5.0

before_cache:
  # See https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs sudo rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs sudo rm

cache:
  directories:
   - "$HOME/.ivy2/cache"
   - "$HOME/.sbt/boot"
